# -*- coding: utf-8 -*-
"""Untitled53.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g8O2QLYOlZMKEtBsyRTap8UnL1Ak67-j
"""

import os
print(os.listdir('.'))

import pandas as pd

df = pd.read_csv('seasonal_agriculture_performance_dataset.csv')
print(df.info())
print("\n--- Summary ---")
print(df.head(2))

"""# **Phase 1: Data Cleaning & Preparation**

# **Handle** **missing** **values** (**e**.**g**., **Rainfall_mm**, **Soil_Moisture_pct**, **and** **Yield_Tonnes_Ha** **have** **slight** **missing** **data** **in** **the** 4,**000**-**row** **dataset**).

# **Validate** **data** **types** **and** **standardize** **categorical** **variables** **like** **Season**, **Irrigation_Method**, **and** **Crop**.
"""

import pandas as pd

# Load dataset
df = pd.read_csv('seasonal_agriculture_performance_dataset.csv')

# 1. Missing Values
missing_info = df.isnull().sum()
missing_cols = missing_info[missing_info > 0]

# 2. Duplicates
duplicates = df.duplicated().sum()

# 3. Categorical Check
seasons = df['Season'].unique()
irrigation = df['Irrigation_Method'].unique()

print("Missing Values:")
print(missing_cols)
print(f"\nTotal Duplicates: {duplicates}")
print(f"\nUnique Seasons: {seasons}")
print(f"Unique Irrigation Methods: {irrigation}")

# Perform basic cleaning for demonstration and summary
# Fill missing Rainfall, Soil Moisture, and Yield with median
df['Rainfall_mm'] = df['Rainfall_mm'].fillna(df['Rainfall_mm'].median())
df['Soil_Moisture_pct'] = df['Soil_Moisture_pct'].fillna(df['Soil_Moisture_pct'].median())
df['Yield_Tonnes_Ha'] = df['Yield_Tonnes_Ha'].fillna(df['Yield_Tonnes_Ha'].median())

print(f"\nMissing values after cleaning: {df.isnull().sum().sum()}")

"""The data cleaning and preparation phase is complete. Here is the breakdown of the initial data state and the steps taken to prepare it for analysis:

Missing Value Identification: Out of 4,000 records, there were 48 missing values in Rainfall_mm, 40 in Soil_Moisture_pct, and 32 in Yield_Tonnes_Ha.

Imputation Strategy: Since these are continuous numerical variables that can be affected by outliers (like extreme weather events), all missing values were imputed using the median of their respective columns. The dataset now has zero missing values.

Duplicate Check: The dataset was scanned for duplicate rows, and 0 duplicates were found. Every record represents a unique entry.

Categorical Validation: The core categorical columns were verified for consistency. No structural errors or misspellings were found.

Seasons: Limited cleanly to three standard categories: 'Kharif', 'Rabi', and 'Zaid'.

Irrigation Methods: Cleanly categorized into 'Drip', 'Flood', 'Rainfed', and 'Sprinkler'.

# **Phase 2: Exploratory Data Analysis (EDA)Map out distributions of environmental conditions (temperature, rainfall, soil moisture) across different seasons.  Analyze the variation of resources used (water, fertilizers, pesticides) grouped by season and region.**
"""

import pandas as pd

# Load and clean data
df = pd.read_csv('seasonal_agriculture_performance_dataset.csv')
df['Rainfall_mm'] = df['Rainfall_mm'].fillna(df['Rainfall_mm'].median())
df['Soil_Moisture_pct'] = df['Soil_Moisture_pct'].fillna(df['Soil_Moisture_pct'].median())
df['Yield_Tonnes_Ha'] = df['Yield_Tonnes_Ha'].fillna(df['Yield_Tonnes_Ha'].median())

# Environmental conditions by season
env_cols = ['Avg_Temperature_C', 'Rainfall_mm', 'Soil_Moisture_pct', 'Sunlight_Hours_Day']
env_summary = df.groupby('Season')[env_cols].mean().round(2)

# Resource usage by season
res_cols = ['Water_Used_m3', 'Fertilizer_kg_ha', 'Pesticide_Litre_ha']
res_summary = df.groupby('Season')[res_cols].mean().round(2)

# Count of records per season to understand distribution
counts = df['Season'].value_counts()

print("--- Distribution of Records ---")
print(counts)
print("\n--- Environmental Conditions (Mean) ---")
print(env_summary)
print("\n--- Resource Usage (Mean) ---")
print(res_summary)

"""Record Distribution Across Seasons The dataset of 4,000 records reflects typical agricultural activity cycles, heavily weighted toward the two primary Indian agricultural seasons:
•	Kharif: 1,779 records (44.5%)
•	Rabi: 1,627 records (40.7%)
•	Zaid: 594 records (14.8%)
Environmental Conditions by Season The analysis confirms distinct environmental variations that drive seasonal agricultural activities:
Season	Avg Temperature (°C)	Rainfall (mm)	Soil Moisture (%)	Sunlight (Hours/Day)
Kharif	28.45	849.20	31.15	6.79
Rabi	23.49	437.62	24.07	7.59
Zaid	31.04	304.65	19.28	8.18

Kharif experiences the highest average rainfall (849.20 mm) and soil moisture (31.15%), aligning with monsoon conditions.

Rabi presents the coolest average temperatures (23.49 °C) and moderate rainfall (437.62 mm).

Zaid features the hottest conditions (31.04 °C), the longest sunlight exposure (8.18 hours), and the lowest natural moisture levels (304.65 mm rainfall, 19.28% soil moisture).

Resource Usage by Season Despite the significant differences in natural rainfall, the average usage of chemical inputs remains relatively constant, while total water usage fluctuates:
Season	Water Used (m³)	Fertilizer (kg/ha)	Pesticide (Liters/ha)
Kharif	6102.20	187.08	5.08
Rabi	5846.99	185.41	5.02
Zaid	6419.89	184.64	5.17

Water Usage: Zaid requires the highest volume of applied water (6,419.89 m³) to compensate for low rainfall and high temperatures, whereas Rabi requires the least (5,846.99 m³).

Chemical Inputs: Fertilizer application ranges tightly between 184.64 kg/ha and 187.08 kg/ha, and pesticide usage remains nearly flat at ~5 Liters/ha across all seasons.

# **Phase 3: Economic & Performance EvaluationCalculate and visualize average Yield_Tonnes_Ha, Revenue_INR, and Profit_INR across Kharif, Rabi, and other seasons to understand how economic outcomes vary.  Assess the relationship between environmental conditions, pest risk, and final yield.**
"""

import pandas as pd

# Load and clean data
df = pd.read_csv('seasonal_agriculture_performance_dataset.csv')
df['Rainfall_mm'] = df['Rainfall_mm'].fillna(df['Rainfall_mm'].median())
df['Soil_Moisture_pct'] = df['Soil_Moisture_pct'].fillna(df['Soil_Moisture_pct'].median())
df['Yield_Tonnes_Ha'] = df['Yield_Tonnes_Ha'].fillna(df['Yield_Tonnes_Ha'].median())

# Economic outcomes by season
econ_cols = ['Yield_Tonnes_Ha', 'Total_Cost_INR', 'Revenue_INR', 'Profit_INR']
econ_summary = df.groupby('Season')[econ_cols].mean().round(2)

print("--- Economic & Performance Outcomes by Season (Mean) ---")
print(econ_summary)

# Correlation analysis for Yield and key factors
corr_cols = ['Yield_Tonnes_Ha', 'Disease_Pest_Risk_pct', 'Avg_Temperature_C', 'Rainfall_mm', 'Soil_Moisture_pct']
correlations = df[corr_cols].corr()['Yield_Tonnes_Ha'].round(3)

print("\n--- Correlation with Yield_Tonnes_Ha ---")
print(correlations)

# Check crop distribution and profit by season
crop_season = df.groupby(['Season', 'Crop'])[['Yield_Tonnes_Ha', 'Profit_INR']].mean().round(2)
print("--- Top Crops by Profit per Season ---")
print(crop_season)

"""Economic & Performance Outcomes by Season Agricultural profitability and crop yields show stark contrasts across the three main seasons, revealing significant variations in economic outcomes.
Season	Yield (Tonnes/Ha)	Total Cost (INR)	Revenue (INR)	Profit (INR)
Kharif	5.63	531,804	710,719	178,914
Rabi	5.04	513,836	601,526	87,689
Zaid	4.64	543,976	519,171	-24,804

Kharif Dominance: The Kharif season generates the highest average yield (5.63 Tonnes/Ha) and the highest average profit (178,914 INR). The favorable monsoon conditions observed in Phase 2 likely contribute to this superior performance.

Zaid Season Deficit: The Zaid season is the most resource-intensive (highest water usage and high average costs of 543,976 INR) but produces the lowest average yield and revenue, resulting in a net average loss (-24,804 INR).

Correlation and Yield DriversWhen testing for linear relationships between environmental conditions and final yield, the direct correlations are exceptionally weak across the aggregate dataset:Rainfall: 0.031Disease/Pest Risk: 0.014Soil Moisture: 0.011Avg Temperature: 0.010This lack of linear correlation indicates that yield and profitability are not driven purely by baseline weather metrics, but rather by the crop selection adapted to those seasons.

Profitability by Crop Type
A deeper breakdown reveals that economic performance is highly segmented by crop category rather than seasonal weather alone:

Cash Crops Drive Profit: Sugarcane (averaging over 700,000 INR profit across seasons) and Chilli (averaging over 600,000 INR profit) are the primary drivers of positive economic performance.

Staple Crops Run at a Loss: High-volume staple crops like Wheat, Rice, and Maize consistently show net average losses across all three seasons in this dataset. For instance, Wheat operates at an average loss of -105,871 INR in Kharif, worsening to -193,208 INR during the harsh Zaid season.

# **Phase 4: Synthesis & RecommendationsIdentify significant seasonal patterns or unusual anomalies.  Develop evidence-based recommendations for seasonal agricultural planning.**
"""

import pandas as pd

# Load and prepare data
df = pd.read_csv('seasonal_agriculture_performance_dataset.csv')
df['Rainfall_mm'] = df['Rainfall_mm'].fillna(df['Rainfall_mm'].median())
df['Soil_Moisture_pct'] = df['Soil_Moisture_pct'].fillna(df['Soil_Moisture_pct'].median())
df['Yield_Tonnes_Ha'] = df['Yield_Tonnes_Ha'].fillna(df['Yield_Tonnes_Ha'].median())

# Synthesis Table 1: Overall Seasonal Efficiency
seasonal_efficiency = df.groupby('Season').agg(
    Avg_Yield_Tonnes_Ha=('Yield_Tonnes_Ha', 'mean'),
    Avg_Water_Used_m3=('Water_Used_m3', 'mean'),
    Avg_Profit_INR=('Profit_INR', 'mean')
).round(2)

# Synthesis Table 2: High vs Low Profit Crops in Zaid (The toughest season)
zaid_crops = df[df['Season'] == 'Zaid'].groupby('Crop').agg(
    Avg_Profit=('Profit_INR', 'mean'),
    Avg_Cost=('Total_Cost_INR', 'mean')
).sort_values(by='Avg_Profit', ascending=False).round(2)

print("--- Seasonal Efficiency Summary ---")
print(seasonal_efficiency)
print("\n--- Zaid Season Crop Performance ---")
print(zaid_crops)

"""The final phase of the project synthesizes the observed seasonal differences and provides evidence-based recommendations for agricultural planning.

Synthesis of Key Findings Seasonal Profitability Gap: Agricultural performance changes drastically across seasons, with Kharif generating the highest average profit (178,914.65 INR) and Zaid resulting in an average net loss (-24,804.82 INR).  Resource Inefficiency in Zaid: The Zaid season requires the highest water usage (6,419.89 m³) to combat high temperatures and low rainfall but yields the lowest production (4.64 Tonnes/Ha).  Crop-Specific Economic Viability: Profitability is heavily dependent on crop selection rather than general seasonal conditions. Cash crops like Sugarcane and Chilli maintain high profitability across all seasons, while staples like Rice, Maize, and Wheat operate at a consistent loss, peaking in the Zaid season.

Data-Driven Recommendations for Agricultural PlanningRestrict Water-Intensive Staples in Zaid: Farmers should avoid planting Rice and Maize during the Zaid season, as these crops require massive water inputs (averaging over 6,400 m³) and result in severe financial losses (e.g., Rice averages a -227,239.34 INR loss in Zaid).Prioritize Cash Crops for Financial Stability: To offset the high baseline costs of farming (averaging over 500,000 INR per season), prioritize the cultivation of Sugarcane and Chilli, which remain heavily profitable regardless of the seasonal environmental variations.  Optimize Kharif for Maximum Yield: Since Kharif offers the most favorable natural environmental conditions (highest rainfall and soil moisture), resources should be heavily allocated to this season to maximize total annual yield and create a financial buffer for the more difficult Zaid season.
"""

import pandas as pd

# 1. Load and prepare data
df = pd.read_csv('seasonal_agriculture_performance_dataset.csv')

# Handle missing values using medians
df['Rainfall_mm'] = df['Rainfall_mm'].fillna(df['Rainfall_mm'].median())
df['Soil_Moisture_pct'] = df['Soil_Moisture_pct'].fillna(df['Soil_Moisture_pct'].median())
df['Yield_Tonnes_Ha'] = df['Yield_Tonnes_Ha'].fillna(df['Yield_Tonnes_Ha'].median())

# 2. Synthesis Table 1: Overall Seasonal Efficiency
# Investigating how agricultural performance varies across seasons
seasonal_efficiency = df.groupby('Season').agg(
    Avg_Yield_Tonnes_Ha=('Yield_Tonnes_Ha', 'mean'),
    Avg_Water_Used_m3=('Water_Used_m3', 'mean'),
    Avg_Cost_INR=('Total_Cost_INR', 'mean'),
    Avg_Profit_INR=('Profit_INR', 'mean')
).round(2)

print("--- Seasonal Efficiency Summary ---")
print(seasonal_efficiency)

# 3. Synthesis Table 2: High vs Low Profit Crops in Zaid
# Identifying unusual or unexpected seasonal patterns (highest losses)
zaid_crops = df[df['Season'] == 'Zaid'].groupby('Crop').agg(
    Avg_Yield=('Yield_Tonnes_Ha', 'mean'),
    Avg_Cost=('Total_Cost_INR', 'mean'),
    Avg_Profit=('Profit_INR', 'mean')
).sort_values(by='Avg_Profit', ascending=False).round(2)

print("\n--- Zaid Season Crop Performance ---")
print(zaid_crops)

"""# **Phase 5: Data Visualization**"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load and prepare data
df = pd.read_csv('seasonal_agriculture_performance_dataset.csv')
df['Rainfall_mm'] = df['Rainfall_mm'].fillna(df['Rainfall_mm'].median())
df['Soil_Moisture_pct'] = df['Soil_Moisture_pct'].fillna(df['Soil_Moisture_pct'].median())
df['Yield_Tonnes_Ha'] = df['Yield_Tonnes_Ha'].fillna(df['Yield_Tonnes_Ha'].median())

# Test plot creation
fig, ax = plt.subplots(figsize=(8, 5))
sns.barplot(data=df, x='Season', y='Profit_INR', errorbar=None, palette='viridis', ax=ax)
ax.set_title('Average Profit by Season')
plt.tight_layout()
plt.savefig('profit_by_season.png')
print("Plot saved successfully.")

"""# **To fulfill the final objectives outlined in the project guidelines, we must now apply appropriate statistical and visualization techniques**"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load and Prepare Data
df = pd.read_csv('seasonal_agriculture_performance_dataset.csv')
df['Rainfall_mm'] = df['Rainfall_mm'].fillna(df['Rainfall_mm'].median())
df['Soil_Moisture_pct'] = df['Soil_Moisture_pct'].fillna(df['Soil_Moisture_pct'].median())
df['Yield_Tonnes_Ha'] = df['Yield_Tonnes_Ha'].fillna(df['Yield_Tonnes_Ha'].median())

# Set visualization style
sns.set_theme(style="whitegrid")
plt.figure(figsize=(18, 5))

# Chart 1: Average Profit by Season
plt.subplot(1, 3, 1)
sns.barplot(data=df, x='Season', y='Profit_INR', errorbar=None, palette='viridis', hue='Season', legend=False)
plt.title('Average Profit by Season', fontsize=14, fontweight='bold')
plt.ylabel('Profit (INR)')
plt.xlabel('Season')

# Chart 2: Water Usage vs. Rainfall across Seasons
plt.subplot(1, 3, 2)
sns.scatterplot(data=df, x='Rainfall_mm', y='Water_Used_m3', hue='Season', palette='deep', alpha=0.6)
plt.title('Rainfall vs Applied Water Usage', fontsize=14, fontweight='bold')
plt.ylabel('Water Used (m³)')
plt.xlabel('Rainfall (mm)')

# Chart 3: Crop Profitability in the Zaid Season
plt.subplot(1, 3, 3)
zaid_data = df[df['Season'] == 'Zaid']
sns.barplot(data=zaid_data, x='Profit_INR', y='Crop', errorbar=None, palette='coolwarm_r', hue='Crop', legend=False)
plt.title('Crop Profitability (Zaid Season Only)', fontsize=14, fontweight='bold')
plt.ylabel('Crop Type')
plt.xlabel('Profit (INR)')

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Select only numerical columns for correlation calculation
numeric_df = df.select_dtypes(include=['float64', 'int64'])

# Calculate the correlation matrix
corr_matrix = numeric_df.corr()

# Set up the matplotlib figure and a heatmap
plt.figure(figsize=(20, 16))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5, cbar_kws={'label': 'Correlation Coefficient'})
plt.title('Correlation Heatmap of Numerical Variables', fontsize=18)
plt.xticks(rotation=90, fontsize=10)
plt.yticks(rotation=0, fontsize=10)
plt.tight_layout()
plt.show()

"""Based on the correlation heatmap and the corr_matrix in the kernel, the variables most strongly correlated with Profit_INR are:

Revenue_INR: 0.99 (Very strong positive correlation)
Total_Cost_INR: 0.89 (Strong positive correlation)
Water_Used_m3: 0.49 (Moderate positive correlation)
Production_Tonnes: 0.39 (Moderate positive correlation)
Market_Price_INR_Tonne: 0.34 (Moderate positive correlation)
This indicates that as revenue and total cost increase, profit tends to increase significantly. Water usage, production, and market price also show a positive, though less pronounced, relationship with profit.

# **scatter plot of Revenue_INR versus Profit_INR**
"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 7))
sns.scatterplot(data=df, x='Revenue_INR', y='Profit_INR', alpha=0.6, hue='Season', palette='viridis')
plt.title('Revenue vs. Profit (INR)', fontsize=16)
plt.xlabel('Revenue (INR)', fontsize=12)
plt.ylabel('Profit (INR)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""# **Phase 6 :Conclusion & Recommendations Summarize the evidence-based insights: Kharif is the most profitable season, while staple crops in the Zaid season lead to heavy financial losses.  Provide the final recommendation: Restrict water-intensive staples during Zaid and prioritize resilient cash crops like Sugarcane and Chilli to maintain year-round financial stability.**"""

import pandas as pd

# Load data
df = pd.read_csv('seasonal_agriculture_performance_dataset.csv')

# Calculate supporting metrics
kharif_profit = df[df['Season'] == 'Kharif']['Profit_INR'].mean()
zaid_staples = df[(df['Season'] == 'Zaid') & (df['Crop'].isin(['Rice', 'Wheat', 'Maize']))]['Profit_INR'].mean()
cash_crops = df[df['Crop'].isin(['Sugarcane', 'Chilli'])]['Profit_INR'].mean()

# Define conclusion text
conclusion = f"""
CONCLUSION & RECOMMENDATIONS

Evidence-Based Insights:
1. Kharif is the most profitable season (Average Profit: {kharif_profit:,.2f} INR).
2. Cultivating staple crops in the Zaid season leads to heavy financial losses (Average Loss: {zaid_staples:,.2f} INR).

Final Recommendations:
1. Restrict water-intensive staples during the Zaid season to mitigate extreme resource costs.
2. Prioritize resilient cash crops like Sugarcane and Chilli (Average Year-Round Profit: {cash_crops:,.2f} INR) to maintain financial stability.
"""

# Print to console
print(conclusion)

# Save to a text file for final project submission
with open('Final_Recommendations.txt', 'w') as file:
    file.write(conclusion)

"""## Conclusion and Recommendation Matrix

### Evidence-Based Insights:
1. Kharif is the most profitable season (Average Profit: 178,914.65 INR).
2. Cultivating staple crops in the Zaid season leads to heavy financial losses (Average Loss: -206,277.87 INR).

### Final Recommendations:
1. Restrict water-intensive staples during the Zaid season to mitigate extreme resource costs.
2. Prioritize resilient cash crops like Sugarcane and Chilli (Average Year-Round Profit: 779,085.37 INR) to maintain financial stability.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Ensure df is loaded and cleaned as per previous steps
df = pd.read_csv('seasonal_agriculture_performance_dataset.csv')
df['Rainfall_mm'] = df['Rainfall_mm'].fillna(df['Rainfall_mm'].median())
df['Soil_Moisture_pct'] = df['Soil_Moisture_pct'].fillna(df['Soil_Moisture_pct'].median())
df['Yield_Tonnes_Ha'] = df['Yield_Tonnes_Ha'].fillna(df['Yield_Tonnes_Ha'].median())

sns.set_theme(style="whitegrid")

plt.figure(figsize=(16, 7))

# Subplot 1: Average Profit by Season
plt.subplot(1, 2, 1)
sns.barplot(data=df, x='Season', y='Profit_INR', errorbar=None, palette='viridis', hue='Season', legend=False)
plt.title('Average Profit by Season (Highlighting Kharif vs. Zaid)', fontsize=14, fontweight='bold')
plt.xlabel('Season', fontsize=12)
plt.ylabel('Average Profit (INR)', fontsize=12)
plt.axhline(0, color='grey', linestyle='--', linewidth=0.8) # Add a zero line

# Subplot 2: Crop Profitability in Zaid Season
plt.subplot(1, 2, 2)
zaid_data = df[df['Season'] == 'Zaid'].groupby('Crop')['Profit_INR'].mean().sort_values(ascending=False).reset_index()
sns.barplot(data=zaid_data, x='Profit_INR', y='Crop', errorbar=None, palette='coolwarm_r', hue='Crop', legend=False)
plt.title('Crop Profitability in Zaid Season (Staples vs. Cash Crops)', fontsize=14, fontweight='bold')
plt.xlabel('Average Profit (INR)', fontsize=12)
plt.ylabel('Crop Type', fontsize=12)
plt.axvline(0, color='grey', linestyle='--', linewidth=0.8) # Add a zero line

plt.tight_layout()
plt.show()